name: Laravel Test deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: hms-db
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_PASSWORD: hmsdb123!@#
          MYSQL_ROOT_USER: root
          MYSQL_USER: hms
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Copy .env from .env.example
        run: composer run-script post-root-package-install

      - name: config clear
        run: php artisan config:clear
        
      - name: Verify MySQL connection
        run: |
          mysql --host 127.0.0.1 --port 3306 -uroot -psecret -e "SHOW DATABASES"
          
      - name: Migrate database
        run: php artisan migrate
